--NAME = GITANSH MITTAL
--
--STUDENT ID = 301200517
--
--MIDTERN TEST ADVANCE DATABASE
--
--
--ANSWER 1ST:
SET SERVEROUTPUT ON;

SELECT UNIQUE(OFFICERS.OFFICER_ID), OFFICERS.FIRST, OFFICERS.LAST
FROM OFFICERS
JOIN CRIME_OFFICERS ON OFFICERS.OFFICER_ID = CRIME_OFFICERS.OFFICER_ID
WHERE CRIME_OFFICERS.OFFICER_ID IN (
SELECT OFFICER_ID 
FROM CRIME_OFFICERS GROUP BY OFFICER_ID
HAVING COUNT(*) > (SELECT AVG(C) FROM (
    SELECT COUNT(CRIME_OFFICERS.CRIME_ID) C
    FROM CRIME_OFFICERS
    GROUP BY CRIME_OFFICERS.OFFICER_ID
)));

--ANSWER 2ND:
SELECT PROB_OFFICERS.LAST, PROB_OFFICERS.PROB_ID 
FROM PROB_OFFICERS
WHERE PROB_ID IN (SELECT PROB_ID FROM  SENTENCES GROUP BY PROB_ID HAVING 
COUNT(PROB_ID) <  (SELECT AVG(COUNT(PROB_ID))FROM SENTENCES GROUP BY PROB_ID));

--ANSWER 3RD:
--# FOR FIRST INPUT TRY (B,500)
DECLARE
    DONOR_TYPE DD_DONOR.TYPECODE%TYPE;
    PLEDGE_AMT DD_PLEDGE.PLEDGEAMT%TYPE;
--  USING CURSOR  
    CURSOR CURSOR_ONE IS
    SELECT DD_DONOR.FIRSTNAME, DD_DONOR.LASTNAME, DD_PLEDGE.PLEDGEAMT
    FROM DD_DONOR
    JOIN DD_PLEDGE ON DD_DONOR.IDDONOR = DD_PLEDGE.IDDONOR
    WHERE DD_DONOR.TYPECODE = DONOR_TYPE;
--    USING COLLECTION
    TYPE COLLECTION_ONE IS RECORD(
    FIRST DD_DONOR.FIRSTNAME%TYPE,
    LAST DD_DONOR.LASTNAME%TYPE,
    AMT DD_PLEDGE.PLEDGEAMT%TYPE
    );
    
    DONOR_REC COLLECTION_ONE;
BEGIN
    DONOR_TYPE:= 'B';
    PLEDGE_AMT:= '500';
    
    OPEN CURSOR_ONE;
    
    LOOP
        
        FETCH CURSOR_ONE INTO DONOR_REC;
        EXIT WHEN CURSOR_ONE%NOTFOUND;
        
        IF DONOR_REC.AMT > PLEDGE_AMT THEN
            DBMS_OUTPUT.PUT_LINE('FIRST NAME: ' || DONOR_REC.FIRST || ' ' || DONOR_REC.LAST ||'  '|| 'PLEDGE AMOUNT: ' || DONOR_REC.AMT); 
      END IF;
    END LOOP;
    
    CLOSE CURSOR_ONE;

END;



--FOR SECOND INPUT TRY(I,250):
DECLARE
    DONOR_TYPE DD_DONOR.TYPECODE%TYPE;
    PLEDGE_AMT DD_PLEDGE.PLEDGEAMT%TYPE;
--  USING CURSOR  
    CURSOR CURSOR_ONE IS
    SELECT DD_DONOR.FIRSTNAME, DD_DONOR.LASTNAME, DD_PLEDGE.PLEDGEAMT
    FROM DD_DONOR
    JOIN DD_PLEDGE ON DD_DONOR.IDDONOR = DD_PLEDGE.IDDONOR
    WHERE DD_DONOR.TYPECODE = DONOR_TYPE;
--    USING COLLECTION
    TYPE COLLECTION_ONE IS RECORD(
    FIRST DD_DONOR.FIRSTNAME%TYPE,
    LAST DD_DONOR.LASTNAME%TYPE,
    AMT DD_PLEDGE.PLEDGEAMT%TYPE
    );
    
    DONOR_REC COLLECTION_ONE;
BEGIN
    DONOR_TYPE:= 'I';
    PLEDGE_AMT:= '250';
    
    OPEN CURSOR_ONE;
    
    LOOP
        
        FETCH CURSOR_ONE INTO DONOR_REC;
        EXIT WHEN CURSOR_ONE%NOTFOUND;
        
        IF DONOR_REC.AMT > PLEDGE_AMT THEN
            DBMS_OUTPUT.PUT_LINE('FIRST NAME: ' || DONOR_REC.FIRST || ' ' || DONOR_REC.LAST ||'  '|| 'PLEDGE AMOUNT: ' || DONOR_REC.AMT); 
      END IF;
    END LOOP;
    
    CLOSE CURSOR_ONE;

END;